name: Terraform CI/CD

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: terraform-main
  cancel-in-progress: false

jobs:
  terraform-validate:
    name: Terraform Validate
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/environment/dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive ../..

      - name: Create Terraform variables
        run: cp terraform.tfvars.example terraform.tfvars

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate


  terraform-plan:
    name: Terraform Plan
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: terraform/environment/dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::194722443160:role/GitHubActions-Terraform-CloudProvisioner
          aws-region: us-east-1

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Terraform Format Check
        run: terraform fmt -check -recursive ../..

      - name: Create Terraform variables
        run: cp terraform.tfvars.example terraform.tfvars

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: terraform/environment/dev/tfplan


  terraform-apply:
    name: Terraform Apply
    needs: terraform-plan
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    environment:
      name: terraform-apply

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: terraform/environment/dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Debug OIDC Claims
        shell: bash
        run: |
          set -euo pipefail

          response=$(curl -sS \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sts.amazonaws.com")

          token=$(echo "$response" | jq -r '.value')

          TOKEN="$token" python - <<'PY'
          import os
          import json
          import base64

          token = os.environ["TOKEN"]
          payload = token.split(".")[1]
          payload += "=" * (-len(payload) % 4)

          claims = json.loads(
              base64.urlsafe_b64decode(payload)
          )

          for key in [
              "sub",
              "aud",
              "repository",
              "repository_owner",
              "environment"
          ]:
              print(f"{key}: {claims.get(key)}")
          PY

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::194722443160:role/GitHubActions-Terraform-CloudProvisioner
          aws-region: us-east-1

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Create Terraform variables
        run: cp terraform.tfvars.example terraform.tfvars

      - name: Terraform Init
        run: terraform init

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: terraform/environment/dev

      - name: Terraform Apply
        run: terraform apply tfplan